{%- from "etcd/map.jinja" import server with context %}
server:
  target:
    static:
      etcd:
        endpoint:
          {%- set hostname = grains.get('nodename') %}
          {%- for member in server.members %}
            {%- if member.name == hostname %}
          - address: {{ member.host }}
            port: {{ member.port }}
            {%- endif %}
          {%- endfor %}
{% raw %}
  alert:
    EtcdFailedTotalIn5m:
      if: >-
        sum by(method) (rate(etcd_http_failed_total{code!~"4[0-9]{2}"}[5m]))
        / sum by(method) (rate(etcd_http_received_total[5m])) > 0.01
      labels:
        severity: warning
        service: etcd
      annotations:
        summary: 'High number of HTTP requests are failing on etcd'
        description: '{{ $value }}% of requests for {{ $labels.method }} failed on etcd instance {{ $labels.instance }}'
    EtcdServerHasLeader:
      if: 'etcd_server_has_leader != 1'
      labels:
        severity: warning
        service: etcd
      annotations:
        summary: 'Etcd instance lost leader'
        description: 'Etcd {{ $labels.instance }} lost his leader'
    EtcdClusterSmall:
      if: 'count(up{job="etcd"} == 0) > count(up{job="etcd"}) / 2 - 1'
      labels:
        severity: warning
        service: etcd
      annotations:
        summary: 'Etcd cluster small'
        description: 'If one more etcd peer goes down the cluster will be unavailable'
{% endraw %}
